export const words = [
  { id: "foroneself_en_jp", en: "for oneself", ja: "自分自身のために", dir: "en-jp", video: "#" },
  { id: "foroneself_jp_en", en: "for oneself", ja: "自分自身のために", dir: "jp-en", video: "#" },
  { id: "usedtodo_en_jp", en: "used to do", ja: "以前は～したものだ", dir: "en-jp", video: "#" },
  { id: "usedtodo_jp_en", en: "used to do", ja: "以前は～したものだ", dir: "jp-en", video: "#" },
  { id: "beusedtodoing_en_jp", en: "be used to doing", ja: "することに慣れている", dir: "en-jp", video: "#" },
  { id: "beusedtodoing_jp_en", en: "be used to doing", ja: "することに慣れている", dir: "jp-en", video: "#" },
  { id: "tooAtodo_en_jp", en: "too A to do", ja: "...すぎて～できない", dir: "en-jp", video: "#" },
  { id: "tooAtodo_jp_en", en: "too A to do", ja: "...すぎて～できない", dir: "jp-en", video: "#" },
  { id: "Aenoughtodo_en_jp", en: "A enough to do", ja: "～するのに十分なA", dir: "en-jp", video: "#" },
  { id: "Aenoughtodo_jp_en", en: "A enough to do", ja: "～するのに十分なA", dir: "jp-en", video: "#" },
  { id: "lookforA_en_jp", en: "look for A", ja: "Aを探す", dir: "en-jp", video: "#" },
  { id: "lookforA_jp_en", en: "look for A", ja: "Aを探す", dir: "jp-en", video: "#" },
  { id: "easily_en_jp", en: "easily", ja: "簡単に", dir: "en-jp", video: "#" },
  { id: "easily_jp_en", en: "easily", ja: "簡単に", dir: "jp-en", video: "#" },
  { id: "hardly_en_jp", en: "hardly", ja: "ほとんど〜ない", dir: "en-jp", video: "#" },
  { id: "hardly_jp_en", en: "hardly", ja: "ほとんど〜ない", dir: "jp-en", video: "#" },
  { id: "almost_en_jp", en: "almost", ja: "ほとんど", dir: "en-jp", video: "#" },
  { id: "almost_jp_en", en: "almost", ja: "ほとんど", dir: "jp-en", video: "#" },
  { id: "already_en_jp", en: "already", ja: "すでに", dir: "en-jp", video: "#" },
  { id: "already_jp_en", en: "already", ja: "すでに", dir: "jp-en", video: "#" },
  { id: "yet_en_jp", en: "yet", ja: "まだ（否定・疑問）", dir: "en-jp", video: "#" },
  { id: "yet_jp_en", en: "yet", ja: "まだ（否定・疑問）", dir: "jp-en", video: "#" },
  { id: "still_en_jp", en: "still", ja: "まだ（継続）", dir: "en-jp", video: "#" },
  { id: "still_jp_en", en: "still", ja: "まだ（継続）", dir: "jp-en", video: "#" },
  { id: "even_en_jp", en: "even", ja: "〜でさえ", dir: "en-jp", video: "#" },
  { id: "even_jp_en", en: "even", ja: "〜でさえ", dir: "jp-en", video: "#" },
  { id: "only_en_jp", en: "only", ja: "ただ〜だけ", dir: "en-jp", video: "#" },
  { id: "only_jp_en", en: "only", ja: "ただ〜だけ", dir: "jp-en", video: "#" },
  { id: "just_en_jp", en: "just", ja: "ちょうど／ただ", dir: "en-jp", video: "#" },
  { id: "just_jp_en", en: "just", ja: "ちょうど／ただ", dir: "jp-en", video: "#" },
  { id: "also_en_jp", en: "also", ja: "〜もまた", dir: "en-jp", video: "#" },
  { id: "also_jp_en", en: "also", ja: "〜もまた", dir: "jp-en", video: "#" },
  { id: "inordertodo_en_jp", en: "in order to do", ja: "〜するために", dir: "en-jp", video: "#" },
  { id: "inordertodo_jp_en", en: "in order to do", ja: "〜するために", dir: "jp-en", video: "#" },
  { id: "sothatSV_en_jp", en: "so that S V", ja: "〜するために", dir: "en-jp", video: "#" },
  { id: "sothatSV_jp_en", en: "so that S V", ja: "〜するために", dir: "jp-en", video: "#" },
  { id: "assoonas_en_jp", en: "as soon as", ja: "〜するとすぐに", dir: "en-jp", video: "#" },
  { id: "assoonas_jp_en", en: "as soon as", ja: "〜するとすぐに", dir: "jp-en", video: "#" },
  { id: "aslongas_en_jp", en: "as long as", ja: "〜する限り", dir: "en-jp", video: "#" },
  { id: "aslongas_jp_en", en: "as long as", ja: "〜する限り", dir: "jp-en", video: "#" },
  { id: "evenif_en_jp", en: "even if", ja: "たとえ〜でも", dir: "en-jp", video: "#" },
  { id: "evenif_jp_en", en: "even if", ja: "たとえ〜でも", dir: "jp-en", video: "#" },
  { id: "ifpossible_en_jp", en: "if possible", ja: "可能であれば", dir: "en-jp", video: "#" },
  { id: "ifpossible_jp_en", en: "if possible", ja: "可能であれば", dir: "jp-en", video: "#" },
  { id: "infact_en_jp", en: "in fact", ja: "実際は", dir: "en-jp", video: "#" },
  { id: "infact_jp_en", en: "in fact", ja: "実際は", dir: "jp-en", video: "#" },
  { id: "forexample_en_jp", en: "for example", ja: "例えば", dir: "en-jp", video: "#" },
  { id: "forexample_jp_en", en: "for example", ja: "例えば", dir: "jp-en", video: "#" },
  { id: "ontheotherhand_en_jp", en: "on the other hand", ja: "一方で", dir: "en-jp", video: "#" },
  { id: "ontheotherhand_jp_en", en: "on the other hand", ja: "一方で", dir: "jp-en", video: "#" },
  { id: "inaddition_en_jp", en: "in addition", ja: "さらに", dir: "en-jp", video: "#" },
  { id: "inaddition_jp_en", en: "in addition", ja: "さらに", dir: "jp-en", video: "#" },
  { id: "asaresult_en_jp", en: "as a result", ja: "結果として", dir: "en-jp", video: "#" },
  { id: "asaresult_jp_en", en: "as a result", ja: "結果として", dir: "jp-en", video: "#" },
  { id: "atleast_en_jp", en: "at least", ja: "少なくとも", dir: "en-jp", video: "#" },
  { id: "atleast_jp_en", en: "at least", ja: "少なくとも", dir: "jp-en", video: "#" },
  { id: "atmost_en_jp", en: "at most", ja: "多くても", dir: "en-jp", video: "#" },
  { id: "atmost_jp_en", en: "at most", ja: "多くても", dir: "jp-en", video: "#" },
  { id: "byoneself_en_jp", en: "by oneself", ja: "自分で", dir: "en-jp", video: "#" },
  { id: "byoneself_jp_en", en: "by oneself", ja: "自分で", dir: "jp-en", video: "#" }
];
