export const words = [
  { id: "takeoffA_en_jp", en: "take off A", ja: "Aを脱ぐ/Aを取り外す", dir: "en-jp", video: "#" },
  { id: "takeoffA_jp_en", en: "take off A", ja: "Aを脱ぐ/Aを取り外す", dir: "jp-en", video: "#" },
  { id: "pickupA_en_jp", en: "pick up A", ja: "Aを拾う/Aを迎えに行く", dir: "en-jp", video: "#" },
  { id: "pickupA_jp_en", en: "pick up A", ja: "Aを拾う/Aを迎えに行く", dir: "jp-en", video: "#" },
  { id: "findoutA_en_jp", en: "find out A", ja: "Aを知る/Aを突き止める", dir: "en-jp", video: "#" },
  { id: "findoutA_jp_en", en: "find out A", ja: "Aを知る/Aを突き止める", dir: "jp-en", video: "#" },
  { id: "filloutA_en_jp", en: "fill out A", ja: "Aに記入する", dir: "en-jp", video: "#" },
  { id: "filloutA_jp_en", en: "fill out A", ja: "Aに記入する", dir: "jp-en", video: "#" },
  { id: "tryonA_en_jp", en: "try on A", ja: "Aを試着する", dir: "en-jp", video: "#" },
  { id: "tryonA_jp_en", en: "try on A", ja: "Aを試着する", dir: "jp-en", video: "#" },
  { id: "growup_en_jp", en: "grow up", ja: "成長する", dir: "en-jp", video: "#" },
  { id: "growup_jp_en", en: "grow up", ja: "成長する", dir: "jp-en", video: "#" },
  { id: "wakeup_en_jp", en: "wake up", ja: "目を覚ます", dir: "en-jp", video: "#" },
  { id: "wakeup_jp_en", en: "wake up", ja: "目を覚ます", dir: "jp-en", video: "#" },
  { id: "hurryup_en_jp", en: "hurry up", ja: "急ぐ", dir: "en-jp", video: "#" },
  { id: "hurryup_jp_en", en: "hurry up", ja: "急ぐ", dir: "jp-en", video: "#" },
  { id: "comeback_en_jp", en: "come back", ja: "戻ってくる", dir: "en-jp", video: "#" },
  { id: "comeback_jp_en", en: "come back", ja: "戻ってくる", dir: "jp-en", video: "#" },
  { id: "goback_en_jp", en: "go back", ja: "戻る", dir: "en-jp", video: "#" },
  { id: "goback_jp_en", en: "go back", ja: "戻る", dir: "jp-en", video: "#" },
  { id: "comefromA_en_jp", en: "come from A", ja: "Aの出身である/Aから来る", dir: "en-jp", video: "#" },
  { id: "comefromA_jp_en", en: "come from A", ja: "Aの出身である/Aから来る", dir: "jp-en", video: "#" },
  { id: "getalongwithA_en_jp", en: "get along with A", ja: "Aとうまくやっていく", dir: "en-jp", video: "#" },
  { id: "getalongwithA_jp_en", en: "get along with A", ja: "Aとうまくやっていく", dir: "jp-en", video: "#" },
  { id: "takepartinA_en_jp", en: "take part in A", ja: "Aに参加する", dir: "en-jp", video: "#" },
  { id: "takepartinA_jp_en", en: "take part in A", ja: "Aに参加する", dir: "jp-en", video: "#" },
  { id: "hearfromA_en_jp", en: "hear from A", ja: "Aから便りをもらう", dir: "en-jp", video: "#" },
  { id: "hearfromA_jp_en", en: "hear from A", ja: "Aから便りをもらう", dir: "jp-en", video: "#" },
  { id: "agreewithA_en_jp", en: "agree with A", ja: "Aに賛成する", dir: "en-jp", video: "#" },
  { id: "agreewithA_jp_en", en: "agree with A", ja: "Aに賛成する", dir: "jp-en", video: "#" },
  { id: "believeinA_en_jp", en: "believe in A", ja: "Aの存在を信じる", dir: "en-jp", video: "#" },
  { id: "believeinA_jp_en", en: "believe in A", ja: "Aの存在を信じる", dir: "jp-en", video: "#" },
  { id: "careaboutA_en_jp", en: "care about A", ja: "Aを気にかける", dir: "en-jp", video: "#" },
  { id: "careaboutA_jp_en", en: "care about A", ja: "Aを気にかける", dir: "jp-en", video: "#" },
  { id: "careforA_en_jp", en: "care for A", ja: "Aの世話をする", dir: "en-jp", video: "#" },
  { id: "careforA_jp_en", en: "care for A", ja: "Aの世話をする", dir: "jp-en", video: "#" },
  { id: "takecareofA_en_jp", en: "take care of A", ja: "Aの世話をする", dir: "en-jp", video: "#" },
  { id: "takecareofA_jp_en", en: "take care of A", ja: "Aの世話をする", dir: "jp-en", video: "#" },
  { id: "payforA_en_jp", en: "pay for A", ja: "Aの代金を支払う", dir: "en-jp", video: "#" },
  { id: "payforA_jp_en", en: "pay for A", ja: "Aの代金を支払う", dir: "jp-en", video: "#" },
  { id: "spendAonB_en_jp", en: "spend A on B", ja: "AをBに費やす", dir: "en-jp", video: "#" },
  { id: "spendAonB_jp_en", en: "spend A on B", ja: "AをBに費やす", dir: "jp-en", video: "#" },
  { id: "spendtimedoing_en_jp", en: "spend time doing", ja: "するのに時間を使う", dir: "en-jp", video: "#" },
  { id: "spendtimedoing_jp_en", en: "spend time doing", ja: "するのに時間を使う", dir: "jp-en", video: "#" },
  { id: "arriveatA_en_jp", en: "arrive at A", ja: "Aに到着する", dir: "en-jp", video: "#" },
  { id: "arriveatA_jp_en", en: "arrive at A", ja: "Aに到着する", dir: "jp-en", video: "#" },
  { id: "arriveinA_en_jp", en: "arrive in A", ja: "Aに到着する", dir: "en-jp", video: "#" },
  { id: "arriveinA_jp_en", en: "arrive in A", ja: "Aに到着する", dir: "jp-en", video: "#" },
  { id: "leaveforA_en_jp", en: "leave for A", ja: "Aに向けて出発する", dir: "en-jp", video: "#" },
  { id: "leaveforA_jp_en", en: "leave for A", ja: "Aに向けて出発する", dir: "jp-en", video: "#" },
  { id: "gettoA_en_jp", en: "get to A", ja: "Aに到着する", dir: "en-jp", video: "#" },
  { id: "gettoA_jp_en", en: "get to A", ja: "Aに到着する", dir: "jp-en", video: "#" },
  { id: "getoffA_en_jp", en: "get off A", ja: "Aを降りる", dir: "en-jp", video: "#" },
  { id: "getoffA_jp_en", en: "get off A", ja: "Aを降りる", dir: "jp-en", video: "#" },
  { id: "turnonA_en_jp", en: "turn on A", ja: "Aのスイッチを入れる", dir: "en-jp", video: "#" },
  { id: "turnonA_jp_en", en: "turn on A", ja: "Aのスイッチを入れる", dir: "jp-en", video: "#" },
  { id: "turnoffA_en_jp", en: "turn off A", ja: "Aのスイッチを切る", dir: "en-jp", video: "#" },
  { id: "turnoffA_jp_en", en: "turn off A", ja: "Aのスイッチを切る", dir: "jp-en", video: "#" },
  { id: "putonA_en_jp", en: "put on A", ja: "Aを身につける", dir: "en-jp", video: "#" },
  { id: "putonA_jp_en", en: "put on A", ja: "Aを身につける", dir: "jp-en", video: "#" }
];
