export const words = [
  { id: "accordingto_en_jp", en: "according to", ja: "〜によると", dir: "en-jp", video: "#" },
  { id: "accordingto_jp_en", en: "according to", ja: "〜によると", dir: "jp-en", video: "#" },
  { id: "insteadof_en_jp", en: "instead of", ja: "〜の代わりに", dir: "en-jp", video: "#" },
  { id: "insteadof_jp_en", en: "instead of", ja: "〜の代わりに", dir: "jp-en", video: "#" },
  { id: "becauseof_en_jp", en: "because of", ja: "〜のために", dir: "en-jp", video: "#" },
  { id: "becauseof_jp_en", en: "because of", ja: "〜のために", dir: "jp-en", video: "#" },
  { id: "thanksto_en_jp", en: "thanks to", ja: "〜のおかげで", dir: "en-jp", video: "#" },
  { id: "thanksto_jp_en", en: "thanks to", ja: "〜のおかげで", dir: "jp-en", video: "#" },
  { id: "suchas_en_jp", en: "such as", ja: "〜のような", dir: "en-jp", video: "#" },
  { id: "suchas_jp_en", en: "such as", ja: "〜のような", dir: "jp-en", video: "#" },
  { id: "aswellas_en_jp", en: "as well as", ja: "〜と同様に", dir: "en-jp", video: "#" },
  { id: "aswellas_jp_en", en: "as well as", ja: "〜と同様に", dir: "jp-en", video: "#" },
  { id: "ratherthan_en_jp", en: "rather than", ja: "〜よりむしろ", dir: "en-jp", video: "#" },
  { id: "ratherthan_jp_en", en: "rather than", ja: "〜よりむしろ", dir: "jp-en", video: "#" },
  { id: "unlike_en_jp", en: "activity", ja: "〜と違って", dir: "en-jp", video: "#" },
  { id: "unlike_jp_en", en: "activity", ja: "〜と違って", dir: "jp-en", video: "#" },
  { id: "within_en_jp", en: "within", ja: "〜以内で", dir: "en-jp", video: "#" },
  { id: "within_jp_en", en: "within", ja: "〜以内で", dir: "jp-en", video: "#" },
  { id: "without_en_jp", en: "without", ja: "〜なしで", dir: "en-jp", video: "#" },
  { id: "without_jp_en", en: "without", ja: "〜なしで", dir: "jp-en", video: "#" },
  { id: "managetodo_en_jp", en: "manage to do", ja: "なんとか〜する", dir: "en-jp", video: "#" },
  { id: "managetodo_jp_en", en: "manage to do", ja: "なんとか〜する", dir: "jp-en", video: "#" },
  { id: "avoiddoing_en_jp", en: "avoid doing", ja: "〜するのを避ける", dir: "en-jp", video: "#" },
  { id: "avoiddoing_jp_en", en: "avoid doing", ja: "〜するのを避ける", dir: "jp-en", video: "#" },
  { id: "denydoing_en_jp", en: "deny doing", ja: "〜したことを否定する", dir: "en-jp", video: "#" },
  { id: "denydoing_jp_en", en: "deny doing", ja: "〜したことを否定する", dir: "jp-en", video: "#" },
  { id: "admitdoing_en_jp", en: "admit doing", ja: "〜したことを認める", dir: "en-jp", video: "#" },
  { id: "admitdoing_jp_en", en: "admit doing", ja: "〜したことを認める", dir: "jp-en", video: "#" },
  { id: "encourageAtodo_en_jp", en: "encourage A to do", ja: "Aに〜するよう励ます", dir: "en-jp", video: "#" },
  { id: "encourageAtodo_jp_en", en: "encourage A to do", ja: "Aに〜するよう励ます", dir: "jp-en", video: "#" },
  { id: "adviseAtodo_en_jp", en: "advise A to do", ja: "Aに〜するよう助言する", dir: "en-jp", video: "#" },
  { id: "adviseAtodo_jp_en", en: "advise A to do", ja: "Aに〜するよう助言する", dir: "jp-en", video: "#" },
  { id: "warnAnottodo_en_jp", en: "warn A not to do", ja: "Aに〜しないよう警告する", dir: "en-jp", video: "#" },
  { id: "warnAnottodo_jp_en", en: "warn A not to do", ja: "Aに〜しないよう警告する", dir: "jp-en", video: "#" },
  { id: "promisetodo_en_jp", en: "promise to do", ja: "〜することを約束する", dir: "en-jp", video: "#" },
  { id: "promisetodo_jp_en", en: "promise to do", ja: "〜することを約束する", dir: "jp-en", video: "#" },
  { id: "refusetodo_en_jp", en: "refuse to do", ja: "〜するのを断る", dir: "en-jp", video: "#" },
  { id: "refusetodo_jp_en", en: "refuse to do", ja: "〜するのを断る", dir: "jp-en", video: "#" },
  { id: "agreetodo_en_jp", en: "agree to do", ja: "〜することに同意する", dir: "en-jp", video: "#" },
  { id: "agreetodo_jp_en", en: "agree to do", ja: "〜することに同意する", dir: "jp-en", video: "#" },
  { id: "plantodo_en_jp", en: "plan to do", ja: "〜する予定である", dir: "en-jp", video: "#" },
  { id: "plantodo_jp_en", en: "plan to do", ja: "〜する予定である", dir: "jp-en", video: "#" },
  { id: "hopetodo_en_jp", en: "hope to do", ja: "〜することを望む", dir: "en-jp", video: "#" },
  { id: "hopetodo_jp_en", en: "hope to do", ja: "〜することを望む", dir: "jp-en", video: "#" },
  { id: "decidetodo_en_jp", en: "decide to do", ja: "〜することを決める", dir: "en-jp", video: "#" },
  { id: "decidetodo_jp_en", en: "decide to do", ja: "〜することを決める", dir: "jp-en", video: "#" },
  { id: "trytodo_en_jp", en: "try to do", ja: "〜しようとする", dir: "en-jp", video: "#" },
  { id: "trytodo_jp_en", en: "try to do", ja: "〜しようとする", dir: "jp-en", video: "#" },
  { id: "needtodo_en_jp", en: "need to do", ja: "〜する必要がある", dir: "en-jp", video: "#" },
  { id: "needtodo_jp_en", en: "need to do", ja: "〜する必要がある", dir: "jp-en", video: "#" },
  { id: "seemtodo_en_jp", en: "seem to do", ja: "〜するように見える", dir: "en-jp", video: "#" },
  { id: "seemtodo_jp_en", en: "seem to do", ja: "〜するように見える", dir: "jp-en", video: "#" },
  { id: "learntodo_en_jp", en: "learn to do", ja: "〜することを学ぶ", dir: "en-jp", video: "#" },
  { id: "learntodo_jp_en", en: "learn to do", ja: "〜することを学ぶ", dir: "jp-en", video: "#" },
  { id: "remembertodo_en_jp", en: "remember to do", ja: "〜するのを忘れずにする", dir: "en-jp", video: "#" },
  { id: "remembertodo_jp_en", en: "remember to do", ja: "〜するのを忘れずにする", dir: "jp-en", video: "#" },
  { id: "forgettodo_en_jp", en: "forget to do", ja: "〜するのを忘れる", dir: "en-jp", video: "#" },
  { id: "forgettodo_jp_en", en: "forget to do", ja: "〜するのを忘れる", dir: "jp-en", video: "#" },
  { id: "stoptodo_en_jp", en: "stop to do", ja: "〜するために立ち止まる", dir: "en-jp", video: "#" },
  { id: "stoptodo_jp_en", en: "stop to do", ja: "〜するために立ち止まる", dir: "jp-en", video: "#" },
  { id: "method_en_jp", en: "method", ja: "方法", dir: "en-jp", video: "#" },
  { id: "method_jp_en", en: "method", ja: "方法", dir: "jp-en", video: "#" },
  { id: "solution_en_jp", en: "solution", ja: "解決策", dir: "en-jp", video: "#" },
  { id: "solution_jp_en", en: "solution", ja: "解決策", dir: "jp-en", video: "#" },
  { id: "issue_en_jp", en: "issue", ja: "問題点", dir: "en-jp", video: "#" },
  { id: "issue_jp_en", en: "issue", ja: "問題点", dir: "jp-en", video: "#" },
  { id: "topic_en_jp", en: "topic", ja: "話題", dir: "en-jp", video: "#" },
  { id: "topic_jp_en", en: "topic", ja: "話題", dir: "jp-en", video: "#" },
  { id: "fact_en_jp", en: "fact", ja: "事実", dir: "en-jp", video: "#" },
  { id: "fact_jp_en", en: "fact", ja: "事実", dir: "jp-en", video: "#" }
];
